/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peliculas;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author equipo hp
 */
public class Rentas extends javax.swing.JFrame {

    private Connection conexion;
    private Statement st;
    private ResultSet rs;


    public void Conectar() {
        try {
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/netflix", "root", "utectulancingo");
            st = conexion.createStatement();

            rs = st.executeQuery("Select * from rentas");

            rs.next(); //recored todos los registros

            this.jTextField1_FECHA.setText(rs.getString("FECHA"));

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error 1" + err.getMessage());
        }

    }

    private void guadarRegistro() {
        try {
            String FECHA = this.jTextField1_FECHA.getText();
            st.executeUpdate("Insert into rentas (FECHA)" + " values ('" + FECHA + "');");
            rs = st.executeQuery("Select * from rentas");

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error 2" + err.getMessage());
        }

    }


    public void llenarCombo() {
        try {
            String sql = "select * from peliculas;";
            rs = st.executeQuery(sql);
            jComboBox1_id_pelicula.removeAllItems();
            while (rs.next()) {
                jComboBox1_id_pelicula.addItem(rs.getString("ID_PELICULA"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 4; " + ex.getMessage());
        }
    }

    private void agregarRegistro() {
        try {
            rs = st.executeQuery("select * from rentas");
            rs.last();
            int id_renta=rs.getInt("ID_RENTA");
            String ID_PELICULA = (String) this.jComboBox1_id_pelicula.getSelectedItem() ;
            st.executeUpdate("Insert into detalle_rentas (ID_RENTA,ID_PELICULA)" + " values ("+id_renta+",'" + ID_PELICULA + "');");

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error 5" + err.getMessage());
        }
    }

    /**
     * Creates new form Rentas
     */
    public Rentas() {
        initComponents();
        Conectar();
        llenarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton1_NUEVO = new javax.swing.JButton();
        jDesktopPane1_RENTAS = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1_FECHA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1_id_pelicula = new javax.swing.JComboBox<>();
        jButton1_AGREGAR = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3_GUARDAR = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton1_NUEVO.setText("NUEVO");
        jButton1_NUEVO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_NUEVOMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1_RENTASLayout = new javax.swing.GroupLayout(jDesktopPane1_RENTAS);
        jDesktopPane1_RENTAS.setLayout(jDesktopPane1_RENTASLayout);
        jDesktopPane1_RENTASLayout.setHorizontalGroup(
            jDesktopPane1_RENTASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1_RENTASLayout.setVerticalGroup(
            jDesktopPane1_RENTASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jLabel1.setText("         RENTAS");

        jLabel2.setText("fecha");

        jLabel3.setText("pelicula");

        jComboBox1_id_pelicula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1_AGREGAR.setText("AGREGAR");
        jButton1_AGREGAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_AGREGARMouseClicked(evt);
            }
        });
        jButton1_AGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_AGREGARActionPerformed(evt);
            }
        });

        jButton2.setText("SALIR");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3_GUARDAR.setText("GUARDAR");
        jButton3_GUARDAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3_GUARDARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1_RENTAS)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(121, 121, 121)
                                    .addComponent(jButton3_GUARDAR))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField1_FECHA, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1_AGREGAR)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1_id_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1_RENTAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1_FECHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3_GUARDAR)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1_id_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton1_AGREGAR)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_NUEVOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_NUEVOMouseClicked
        // TODO add your handling code here
    }//GEN-LAST:event_jButton1_NUEVOMouseClicked

    private void jButton1_AGREGARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_AGREGARMouseClicked
        // TODO add your handling code here:
        agregarRegistro();
    }//GEN-LAST:event_jButton1_AGREGARMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Menu contra = new Menu();
        contra.show();
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3_GUARDARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3_GUARDARMouseClicked
        // TODO add your handling code here:
        guadarRegistro();
    }//GEN-LAST:event_jButton3_GUARDARMouseClicked

    private void jButton1_AGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_AGREGARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_AGREGARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_AGREGAR;
    private javax.swing.JButton jButton1_NUEVO;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3_GUARDAR;
    private javax.swing.JComboBox<String> jComboBox1_id_pelicula;
    private javax.swing.JDesktopPane jDesktopPane1_RENTAS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1_FECHA;
    // End of variables declaration//GEN-END:variables
}
